### PR TITLE
Update library files and update node

### PR DESCRIPTION
**Pull request by truhoang**
Removed old library files and added v3.2.0 library files and associated headers. Also updated leddar.cpp to use new functions

### CODE REVIEW

**Comment by truhoang** [comment]
I haven't tested the code since I don't have access to the sensor on the weekends. I'll compile and test the new codes on Monday and confirm.

**Comment by anassinator** [comment]
Yeah I was about to say that doesn't compile.

I just merged a PR that allows for a custom library directory (#4) BTW. So your PR shouldn't package the lib folder as well as this would only work for x86.

Also, `leddar_main.cpp` should be `leddar.cpp` in order to be compiled with the current CMakeList. That would also make the diffs more readable and easier to review.

Once you've fixed this, let me know and I'll take a look. I'll be busy for the next couple of days however, so this might take a while.

**Comment by truhoang** [comment]
I made all the changes in accordance with the latest merge.

**Comment by anassinator** [comment]
Alright, still doesn't compile though and it still has some merge conflicts. Let me know when you've fixed it.

**Comment by anassinator** [comment]
I think this isn't needed anymore. Thanks though.

**Pull request closed without merging**
